/* Generated By:JavaCC: Do not edit this line. DFPLalgParserConstants.java */
package dfp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DFPLalgParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int LOD = 8;
  /** RegularExpression Id. */
  int IDENTIFIER_MG = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int COMMENT_NF = 11;
  /** RegularExpression Id. */
  int SIMB_NUM_INTEIRO = 12;
  /** RegularExpression Id. */
  int SIMB_NUM_REAL = 13;
  /** RegularExpression Id. */
  int SIMB_NUM_REAL_MF = 14;
  /** RegularExpression Id. */
  int SIMB_ATRIB = 15;
  /** RegularExpression Id. */
  int SIMB_PONTO_VIRGULA = 16;
  /** RegularExpression Id. */
  int SIMB_DOIS_PONTOS = 17;
  /** RegularExpression Id. */
  int SIMB_ABRE_PARENTESE = 18;
  /** RegularExpression Id. */
  int SIMB_FECHA_PARENTESE = 19;
  /** RegularExpression Id. */
  int SIMB_VIRGULA = 20;
  /** RegularExpression Id. */
  int SIMB_PONTO = 21;
  /** RegularExpression Id. */
  int SIMB_RELACAO = 22;
  /** RegularExpression Id. */
  int SIMB_OPP_ADD = 23;
  /** RegularExpression Id. */
  int SIMB_OPP_MUL = 24;
  /** RegularExpression Id. */
  int OTHER = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<DIGIT>",
    "<LETTER>",
    "<LOD>",
    "<IDENTIFIER_MG>",
    "<IDENTIFIER>",
    "<COMMENT_NF>",
    "<SIMB_NUM_INTEIRO>",
    "<SIMB_NUM_REAL>",
    "<SIMB_NUM_REAL_MF>",
    "\":=\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "<SIMB_RELACAO>",
    "<SIMB_OPP_ADD>",
    "<SIMB_OPP_MUL>",
    "<OTHER>",
  };

}
