/* Generated By:JavaCC: Do not edit this line. DFPLalgParserConstants.java */
package dfp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DFPLalgParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIMB_ATRIB = 5;
  /** RegularExpression Id. */
  int SIMB_PONTO_VIRGULA = 6;
  /** RegularExpression Id. */
  int SIMB_DOIS_PONTOS = 7;
  /** RegularExpression Id. */
  int SIMB_ABRE_PARENTESE = 8;
  /** RegularExpression Id. */
  int SIMB_FECHA_PARENTESE = 9;
  /** RegularExpression Id. */
  int SIMB_VIRGULA = 10;
  /** RegularExpression Id. */
  int SIMB_PONTO = 11;
  /** RegularExpression Id. */
  int SIMB_RELACAO = 12;
  /** RegularExpression Id. */
  int SIMB_OPP_ADD = 13;
  /** RegularExpression Id. */
  int SIMB_OPP_MUL = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":=\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "<SIMB_RELACAO>",
    "<SIMB_OPP_ADD>",
    "<SIMB_OPP_MUL>",
  };

}
